Add config file for secret values
hotosm/osmh pull request #4
Opened 2021-11-03 11:28 UTC by eternaltyro

- Add configuration file into which secrets and credentials can be added
  in order to avoid exposing passwords to the terminal
- Modify connection parameters for database to fallback to config file values
- Order of precedence is passed arguments -> ENVVARS -> config file values
- Modify Argparser help strings and defaults
- Add exception handling for psycopg2 connections

2021-11-03 14:28 UTC, omranlm requested changes
Please check the HATABASE_HOST env when picking ENVVAR om config.py

2021-11-03 14:57 UTC, eternaltyro commented on config.py
> +DATABASE_HOST = os.getenv('DATABASE_PASSWORD', _DATABASE_HOST)
Nice catch. delivered a fix. @omranlm

2021-11-05 14:15 UTC, omranlm commented
Fixed another type for frequency and committed change

2021-11-05 14:16 UTC, merged

2021-11-05 14:20 UTC, eternaltyro commented
Thanks for the fix and merge @omranlm